### ISSUE TITLE
Cant launch example project on Ubuntu.

### ISSUE THREAD

**Issue by Murii** [non-dev/nide#2]
Executing '/home/murii/Desktop/SPACE/non.jar desktop:run'
> Checking for latest version TASK DONE
> Checking dependencies and updating data
:update
:android:copyNatives
:android:update
:desktop:update
:ios:update
TASK DONE
> Executing 'gradlew desktop:run'
:core:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:core:processResources UP-TO-DATE
:core:classes
:core:jar
:desktop:compileJava
FAILURE: Build failed with an exception.
* What went wrong:
Could not resolve all dependencies for configuration ':desktop:compile'.
> Could not resolve com.badlogicgames.gdx:gdx-controllers-desktop:1.5.3.
  Required by:
      .non:desktop:1.0.0
   > No cached version of com.badlogicgames.gdx:gdx-controllers-desktop:1.5.3 available for offline mode.
   > No cached version of com.badlogicgames.gdx:gdx-controllers-desktop:1.5.3 available for offline mode.
   > No cached version of com.badlogicgames.gdx:gdx-controllers-desktop:1.5.3 available for offline mode.
> Could not resolve com.badlogicgames.gdx:gdx-controllers-platform:1.5.3.
  Required by:
      .non:desktop:1.0.0
   > No cached version of com.badlogicgames.gdx:gdx-controllers-platform:1.5.3 available for offline mode.
   > No cached version of com.badlogicgames.gdx:gdx-controllers-platform:1.5.3 available for offline mode.
   > No cached version of com.badlogicgames.gdx:gdx-controllers-platform:1.5.3 available for offline mode.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
TASK FAILED
Task finished with non-zero result

BUILD FAILED
Total time: 12 seconds

**Comment by deathbeam** [comment]
Did you ran it with internet available? For first time,  Non tries to download and cache the dependencies from Maven Central.

**Comment by Murii** [comment]
Of course!

**Comment by deathbeam** [comment]
Hmm, okay, I have temporary solution. From command line, navigate to your project directory to .non folder and in it run 

gradlew --refresh-dependencies

I don't know why controllers dependency is ignored. I can fix it in next build, but that will cause slower builds (by only few seconds).

**Comment by Murii** [comment]
No command 'gradlew' found, did you mean:
 Command 'gradle' from package 'gradle' (universe)

**Comment by Murii** [comment]
I`ll wait for a patch from you.

**Comment by deathbeam** [comment]
Try to execute

/home/murii/Desktop/SPACE/.non/gradlew --refresh-dependencies

**Comment by Murii** [comment]
I tried to acces folder gradlew but is not there.Then from .non I gradlew --refresh-dependencies but is not working

**Comment by deathbeam** [comment]
gradlew isn't folder, it is file without extension (it is a shell script but without .sh extension)

**Comment by Murii** [comment]
Yeah,well I tried to be sure

**Comment by deathbeam** [comment]
Okay, fixed it but cannot compile it, so you need to do it manually.
1. Download source code of Non here: https://github.com/non-dev/non
2. Use this tutorial: https://github.com/non-dev/non/wiki/Working-from-Source to create non.jar
3. Replace non.jar in your project directory /home/murii/Desktop/SPACE/

**Comment by deathbeam** [comment]
Closing, fixed this issue with commit 8d254f49519ebcd1c2a30f059eb2a0224eda648a . Check non-dev.github,io for new nide.jar download.
